title: Analysis of cardiovascular & other diseases
description: This is a visualization of how factors like age, weight and exercise could influence a person's ardiovascular and general health. These visualizations are powered by the Cardiovascular Diseases Risk Prediction Dataset available on kaggle.
